//! # QCS OpenAPI client for Rust
//!
//! This crate is autogenerated.
//!
//! ## Quick Start example
//!
//! ```no_run
//! use qcs_api_client_openapi_internal::apis::configuration::Configuration;
//! use qcs_api_client_openapi_internal::apis::default_api::get_health;
//! # #[tokio::main]
//! # async fn main() {
//! let config = Configuration::new().await.expect("should not fail to load config");
//! get_health(&config).await.expect("API should be healthy")
//! # }
//! ```

#![allow(clippy::derive_partial_eq_without_eq)]
#![allow(clippy::clone_double_ref)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::too_many_arguments)]

pub use reqwest;

pub use serde;
pub use serde_json;
pub use url;
pub mod apis;
pub mod models;
pub use qcs_api_client_common as common;
