[bans]
multiple-versions = "warn"
wildcards = "warn"

[advisories]
ignore = [
    "RUSTSEC-2024-0384"  # "instant" is unmaintained, dependency of "backoff", which also appears to be unmaintained
]

[licenses]
allow = [
    "Apache-2.0",
    "ISC",
    "MIT",
    "OpenSSL",
    "BSD-3-Clause",
    "BSL-1.0",
    "Unicode-DFS-2016",
    "Unicode-3.0",
]
