extend = ".rust-ci/defaults/Makefile.toml"

[env]
# Removed --optional-deps from default flags, as only explicit features should be used
CARGO_HACK_COMMON_FLAGS = "--feature-powerset --exclude-features docker"

[config]
default_to_workspace = false
on_error_task = "docker-down"
load_script = """
    if [ ! -d /etc/rust-ci ] || [ -d .rust-ci/.git ]; then
        if [ ! -d .rust-ci ]; then
            git clone git@gitlab.com:rigetti/qcs/utilities/rust-ci-image.git .rust-ci
        else
            git -C .rust-ci pull
        fi
    else
        if [ -d .rust-ci ]; then
            rm -rf .rust-ci
        fi
        cp -r /etc/rust-ci .rust-ci
    fi
"""

[tasks.docker-up]
command = "docker"
args = ["compose", "up", "-d"]

[tasks.docker-down]
command = "docker"
ignore_errors = true
args = ["compose", "down"]

[tasks.docker-logs]
command = "docker"
args = ["compose", "logs"]

[tasks.docker-tests]
command = "cargo"
args = ["test", "-F", "docker", "-p", "proxy-test"]

[tasks.docker-test-flow]
dependencies = ["docker-up", "docker-tests", "docker-logs", "docker-down"]

# See https://daseldocs.tomwright.me/installation
[tasks.install-dasel-linux]
condition = { platforms = ["linux"] }
condition_script = ["command -v dasel && exit 1 || exit 0"]
script = [
    '''
    curl -sSLf "$(curl -sSLf https://api.github.com/repos/tomwright/dasel/releases/latest | grep browser_download_url | grep linux_amd64 | grep -v .gz | cut -d\" -f 4)" -L -o dasel && chmod +x dasel
    mv ./dasel /usr/local/bin/dasel
    '''
]

[tasks.install-dasel-macos]
condition = { platforms = ["mac"] }
condition_script = ["command -v dasel && exit 1 || exit 0"]
command = "brew install dasel"

# used in CI to check dependencies are sorted.
[tasks.install-cargo-sort]
install_crate = { crate_name = "cargo-sort", version = "1.0.9", binary = "cargo", test_arg = ["sort", "--help"] }

[tasks.sort-manifests]
dependencies = ["install-cargo-sort"]
command = "cargo"
args = ["sort", "--workspace"]

[tasks.check-manifests]
dependencies = ["install-cargo-sort"]
command = "cargo"
args = ["sort", "--workspace", "--check"]
