// Copyright 2022 Rigetti Computing
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! # QCS OpenAPI client for Rust
//!
//! This crate is autogenerated.
//!
//! ## Quick Start example
//!
//! ```no_run
//! use qcs_api_client_openapi::apis::configuration::Configuration;
//! use qcs_api_client_openapi::apis::default_api::get_health;
//! # #[tokio::main]
//! # async fn main() {
//! let config = Configuration::new().await.expect("should not fail to load config");
//! get_health(&config).await.expect("API should be healthy");
//! # }
//! ```

#![allow(clippy::derive_partial_eq_without_eq)]
#![allow(suspicious_double_ref_op)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::too_many_arguments)]
#![allow(noop_method_call)]

pub use reqwest;

pub use serde;
pub use serde_json;
pub use url;
pub mod apis;
pub mod models;
pub use qcs_api_client_common as common;

#[cfg(feature = "clap")]
pub mod clap_utils {
    use serde::de::DeserializeOwned;
    use std::str::FromStr;

    pub type JsonMaybeStdin<T> = clap_stdin::MaybeStdin<JsonFromStr<T>>;

    #[derive(Debug, Clone)]
    pub struct JsonFromStr<T>(T)
    where
        T: Clone + DeserializeOwned;

    impl<T> FromStr for JsonFromStr<T>
    where
        T: Clone + DeserializeOwned,
    {
        type Err = anyhow::Error;

        fn from_str(s: &str) -> Result<Self, Self::Err> {
            let d = &mut serde_json::Deserializer::from_str(s);
            let v = serde_path_to_error::deserialize(d).map_err(|e| {
                let full_type_name = std::any::type_name::<T>();
                let simple_type_name = full_type_name.rsplit("::").next().unwrap_or(full_type_name);
                anyhow::anyhow!("Failed to parse {}: {}", simple_type_name, e)
            })?;
            Ok(Self(v))
        }
    }

    impl<T> JsonFromStr<T>
    where
        T: Clone + DeserializeOwned,
    {
        pub fn into_inner(self) -> T {
            self.0
        }
    }
}
