# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from . import configuration
__all__ = [
    "QcsApiClientError",
    "configuration",
]

class QcsApiClientError(builtins.Exception):
    r"""
    Base exception type for errors raised by this package.
    """
    ...

