# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
from . import configuration

class QcsApiClientError(builtins.Exception):
    r"""
    Base exception type for errors raised by this package.
    """
    ...

