"""A suite of common functionalities for QCS client applications.

This package offers reusable middleware implementations
that can be integrated into various client libraries.
This allows for consistent behavior across different projects
and facilitates easier maintenance and scalability of client-side logic.

⚠️ This package is still in early development
and breaking changes should be expected between minor versions.
"""

# Expose the compiled module's contents under the expected namespace.
# Unlike `configuration/__init__.py`, this file is *not* generated by pyo3_stub_gen,
# since it also exposes the pure-Python `grpc` and `httpx` modules.
from . import configuration, grpc, httpx
from ._qcs_api_client_common import QcsApiClientError

__all__ = ["QcsApiClientError", "configuration", "grpc", "httpx"]

